#!/bin/bash

##http://unix.stackexchange.com/questions/2570/execute-nohup-command-with-input


sudo nohup coffee -c -w /root/workspace/severus/*.coffee /root/workspace/severus/lib/*.coffee /root/workspace/severus/public/*.coffee /root/workspace/officelist/*.coffee &


echo "done"
disown $!
#disown $$
wait #http://www.linuxtopia.org/online_books/advanced_bash_scripting_guide/x6632.html
echo "dozzone"
